server:
  port: 10001
spring:
  application:
    name: server-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      # 此节点下的配置是为了解决SpringCloud Gateway跨域的问题
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowCredentials: true
            allowedHeaders: "*"
      # 表示一个路由数组，可以在此节点下配置多个路由信息
      routes:
        - id: user-gateway
          uri: lb://server-user
          # 路由的优先级，数字越小表示优先级越高
          order: 1
          # 网关断言，也就是路由转发的条件，也是一个数组，可以配置多个路由转发条件
          predicates:
            - Path=/server-user/**
          # 网关过滤器，在过滤器中可以修改请求的参数和header信息，以及响应的结果和header信息，网关过滤器也是一个数组，可以配置多个过滤规则
          filters:
            # 网关在进行路由转发之前，会去掉1层访问路径
            - StripPrefix=1

        - id: product-gateway
          uri: lb://server-product
          order: 1
          predicates:
            - Path=/server-product/**
          filters:
            - StripPrefix=1

        - id: order-gateway
          uri: lb://server-order
          order: 1
          predicates:
            - Path=/server-order/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true